version: "3.9"

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    networks:
      - coolify
    ports:
      - "3307:3307"
    environment:
      DB_HOST: s0c8sws804cgw8c0ko8cg4sw
      DB_USER: hackaton
      DB_PASSWORD: #cfvPQcp%Fi2K0
      DB_NAME: crm_hackathon
      DB_PORT: 3306
    restart: always

networks:
  coolify:
    external: true